spring:
  application:
    name: athlete

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

zipkin:
  locator:
    discovery:
      enabled: true